[package]
name = "feel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iso8601 = "0.6.1"
lazy_static = "1.4.0"
regex = "1.10.3"
rust_decimal = "1.34.3"
rust_decimal_macros = "1.34.2"
