[workspace]
resolver = "2"
members = [
        "crates/feel-core",
        "crates/feel",
]

[workspace.dependencies]
chrono = {version="0.4.34"}
iso8601 = {version="0.6.1", features = ["chrono"]}
lazy_static = "1.4.0"
regex = "1.10.3"
rust_decimal_macros = "1.34.2"
feel-core = { path="crates/feel-core" }
serde = {version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
