[package]
name = "anpai"
version = "0.1.0"
edition = "2021"

[dependencies]
feel.workspace = true
serde.workspace = true
clap = { version="4.5.1", features = ["derive"]}
fileinput = "0.3.0"
serde_json.workspace = true
